[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "postillon-newstickers-scraper"
version = "0.1.0"
description = "scrape all Postillon's newstickers from all newsticker's sites."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beanie>=2.0.1",
    "beautifulsoup4>=4.14.3",
    "black>=26.1.0",
    "isort>=7.0.0",
    "motor>=3.7.1",
    "mypy>=1.19.1",
    "opencv-python>=4.13.0.92",
    "pillow>=12.1.0",
    "pydantic>=2.12.5",
    "pytesseract>=0.3.13",
    "pytest>=9.0.2",
    "requests>=2.32.5",
    "setuptools>=81.0.0",
    "types-requests>=2.32.4.20260107",
    "types-setuptools>=80.10.0.20260124",
    "typing-extensions>=4.15.0,<5.0.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "ruff>=0.15.0",
]

# --- THE FIX IS HERE ---
[tool.setuptools]
# We explicitly list the top-level folders you want to include as packages
packages = [
    "models",
    "exceptions",
    "url_builder",
    "newstickers_parsers",
    "urls_to_json_dumper"
]
